// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/labstack/echo/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIHandler creates a new instance of MockIHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHandler {
	mock := &MockIHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIHandler is an autogenerated mock type for the IHandler type
type MockIHandler struct {
	mock.Mock
}

type MockIHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHandler) EXPECT() *MockIHandler_Expecter {
	return &MockIHandler_Expecter{mock: &_m.Mock}
}

// Me provides a mock function for the type MockIHandler
func (_mock *MockIHandler) Me(c *echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHandler_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockIHandler_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - c *echo.Context
func (_e *MockIHandler_Expecter) Me(c interface{}) *MockIHandler_Me_Call {
	return &MockIHandler_Me_Call{Call: _e.mock.On("Me", c)}
}

func (_c *MockIHandler_Me_Call) Run(run func(c *echo.Context)) *MockIHandler_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Context
		if args[0] != nil {
			arg0 = args[0].(*echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_Me_Call) Return(err error) *MockIHandler_Me_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHandler_Me_Call) RunAndReturn(run func(c *echo.Context) error) *MockIHandler_Me_Call {
	_c.Call.Return(run)
	return _c
}

// SignIn provides a mock function for the type MockIHandler
func (_mock *MockIHandler) SignIn(c *echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHandler_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockIHandler_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - c *echo.Context
func (_e *MockIHandler_Expecter) SignIn(c interface{}) *MockIHandler_SignIn_Call {
	return &MockIHandler_SignIn_Call{Call: _e.mock.On("SignIn", c)}
}

func (_c *MockIHandler_SignIn_Call) Run(run func(c *echo.Context)) *MockIHandler_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Context
		if args[0] != nil {
			arg0 = args[0].(*echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_SignIn_Call) Return(err error) *MockIHandler_SignIn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHandler_SignIn_Call) RunAndReturn(run func(c *echo.Context) error) *MockIHandler_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignOut provides a mock function for the type MockIHandler
func (_mock *MockIHandler) SignOut(c *echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for SignOut")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHandler_SignOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignOut'
type MockIHandler_SignOut_Call struct {
	*mock.Call
}

// SignOut is a helper method to define mock.On call
//   - c *echo.Context
func (_e *MockIHandler_Expecter) SignOut(c interface{}) *MockIHandler_SignOut_Call {
	return &MockIHandler_SignOut_Call{Call: _e.mock.On("SignOut", c)}
}

func (_c *MockIHandler_SignOut_Call) Run(run func(c *echo.Context)) *MockIHandler_SignOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Context
		if args[0] != nil {
			arg0 = args[0].(*echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_SignOut_Call) Return(err error) *MockIHandler_SignOut_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHandler_SignOut_Call) RunAndReturn(run func(c *echo.Context) error) *MockIHandler_SignOut_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockIHandler
func (_mock *MockIHandler) SignUp(c *echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHandler_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockIHandler_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - c *echo.Context
func (_e *MockIHandler_Expecter) SignUp(c interface{}) *MockIHandler_SignUp_Call {
	return &MockIHandler_SignUp_Call{Call: _e.mock.On("SignUp", c)}
}

func (_c *MockIHandler_SignUp_Call) Run(run func(c *echo.Context)) *MockIHandler_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Context
		if args[0] != nil {
			arg0 = args[0].(*echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_SignUp_Call) Return(err error) *MockIHandler_SignUp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHandler_SignUp_Call) RunAndReturn(run func(c *echo.Context) error) *MockIHandler_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUsecase creates a new instance of MockIUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUsecase {
	mock := &MockIUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUsecase is an autogenerated mock type for the IUsecase type
type MockIUsecase struct {
	mock.Mock
}

type MockIUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUsecase) EXPECT() *MockIUsecase_Expecter {
	return &MockIUsecase_Expecter{mock: &_m.Mock}
}

// Me provides a mock function for the type MockIUsecase
func (_mock *MockIUsecase) Me(ctx context.Context) (*MeResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 *MeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*MeResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *MeResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUsecase_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockIUsecase_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIUsecase_Expecter) Me(ctx interface{}) *MockIUsecase_Me_Call {
	return &MockIUsecase_Me_Call{Call: _e.mock.On("Me", ctx)}
}

func (_c *MockIUsecase_Me_Call) Run(run func(ctx context.Context)) *MockIUsecase_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUsecase_Me_Call) Return(meResponse *MeResponse, err error) *MockIUsecase_Me_Call {
	_c.Call.Return(meResponse, err)
	return _c
}

func (_c *MockIUsecase_Me_Call) RunAndReturn(run func(ctx context.Context) (*MeResponse, error)) *MockIUsecase_Me_Call {
	_c.Call.Return(run)
	return _c
}

// SignIn provides a mock function for the type MockIUsecase
func (_mock *MockIUsecase) SignIn(ctx context.Context, req SignInRequest) (*SignInResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 *SignInResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SignInRequest) (*SignInResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, SignInRequest) *SignInResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignInResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, SignInRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUsecase_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockIUsecase_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - ctx context.Context
//   - req SignInRequest
func (_e *MockIUsecase_Expecter) SignIn(ctx interface{}, req interface{}) *MockIUsecase_SignIn_Call {
	return &MockIUsecase_SignIn_Call{Call: _e.mock.On("SignIn", ctx, req)}
}

func (_c *MockIUsecase_SignIn_Call) Run(run func(ctx context.Context, req SignInRequest)) *MockIUsecase_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SignInRequest
		if args[1] != nil {
			arg1 = args[1].(SignInRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUsecase_SignIn_Call) Return(signInResponse *SignInResponse, err error) *MockIUsecase_SignIn_Call {
	_c.Call.Return(signInResponse, err)
	return _c
}

func (_c *MockIUsecase_SignIn_Call) RunAndReturn(run func(ctx context.Context, req SignInRequest) (*SignInResponse, error)) *MockIUsecase_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignOut provides a mock function for the type MockIUsecase
func (_mock *MockIUsecase) SignOut(ctx context.Context, req SignOutRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignOut")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SignOutRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUsecase_SignOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignOut'
type MockIUsecase_SignOut_Call struct {
	*mock.Call
}

// SignOut is a helper method to define mock.On call
//   - ctx context.Context
//   - req SignOutRequest
func (_e *MockIUsecase_Expecter) SignOut(ctx interface{}, req interface{}) *MockIUsecase_SignOut_Call {
	return &MockIUsecase_SignOut_Call{Call: _e.mock.On("SignOut", ctx, req)}
}

func (_c *MockIUsecase_SignOut_Call) Run(run func(ctx context.Context, req SignOutRequest)) *MockIUsecase_SignOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SignOutRequest
		if args[1] != nil {
			arg1 = args[1].(SignOutRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUsecase_SignOut_Call) Return(err error) *MockIUsecase_SignOut_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUsecase_SignOut_Call) RunAndReturn(run func(ctx context.Context, req SignOutRequest) error) *MockIUsecase_SignOut_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockIUsecase
func (_mock *MockIUsecase) SignUp(ctx context.Context, req SignUpRequest) (*SignUpResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 *SignUpResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SignUpRequest) (*SignUpResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, SignUpRequest) *SignUpResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignUpResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, SignUpRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUsecase_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockIUsecase_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - req SignUpRequest
func (_e *MockIUsecase_Expecter) SignUp(ctx interface{}, req interface{}) *MockIUsecase_SignUp_Call {
	return &MockIUsecase_SignUp_Call{Call: _e.mock.On("SignUp", ctx, req)}
}

func (_c *MockIUsecase_SignUp_Call) Run(run func(ctx context.Context, req SignUpRequest)) *MockIUsecase_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SignUpRequest
		if args[1] != nil {
			arg1 = args[1].(SignUpRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUsecase_SignUp_Call) Return(signUpResponse *SignUpResponse, err error) *MockIUsecase_SignUp_Call {
	_c.Call.Return(signUpResponse, err)
	return _c
}

func (_c *MockIUsecase_SignUp_Call) RunAndReturn(run func(ctx context.Context, req SignUpRequest) (*SignUpResponse, error)) *MockIUsecase_SignUp_Call {
	_c.Call.Return(run)
	return _c
}
