// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/anonychun/bibit/pkg/pb/api/v1/app/auth"
	"github.com/labstack/echo/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIGrpcHandler creates a new instance of MockIGrpcHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIGrpcHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIGrpcHandler {
	mock := &MockIGrpcHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIGrpcHandler is an autogenerated mock type for the IGrpcHandler type
type MockIGrpcHandler struct {
	mock.Mock
}

type MockIGrpcHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIGrpcHandler) EXPECT() *MockIGrpcHandler_Expecter {
	return &MockIGrpcHandler_Expecter{mock: &_m.Mock}
}

// Me provides a mock function for the type MockIGrpcHandler
func (_mock *MockIGrpcHandler) Me(context1 context.Context, meRequest *auth.MeRequest) (*auth.MeResponse, error) {
	ret := _mock.Called(context1, meRequest)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 *auth.MeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.MeRequest) (*auth.MeResponse, error)); ok {
		return returnFunc(context1, meRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.MeRequest) *auth.MeResponse); ok {
		r0 = returnFunc(context1, meRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.MeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.MeRequest) error); ok {
		r1 = returnFunc(context1, meRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGrpcHandler_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockIGrpcHandler_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - context1 context.Context
//   - meRequest *auth.MeRequest
func (_e *MockIGrpcHandler_Expecter) Me(context1 interface{}, meRequest interface{}) *MockIGrpcHandler_Me_Call {
	return &MockIGrpcHandler_Me_Call{Call: _e.mock.On("Me", context1, meRequest)}
}

func (_c *MockIGrpcHandler_Me_Call) Run(run func(context1 context.Context, meRequest *auth.MeRequest)) *MockIGrpcHandler_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.MeRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.MeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGrpcHandler_Me_Call) Return(meResponse *auth.MeResponse, err error) *MockIGrpcHandler_Me_Call {
	_c.Call.Return(meResponse, err)
	return _c
}

func (_c *MockIGrpcHandler_Me_Call) RunAndReturn(run func(context1 context.Context, meRequest *auth.MeRequest) (*auth.MeResponse, error)) *MockIGrpcHandler_Me_Call {
	_c.Call.Return(run)
	return _c
}

// SignIn provides a mock function for the type MockIGrpcHandler
func (_mock *MockIGrpcHandler) SignIn(context1 context.Context, signInRequest *auth.SignInRequest) (*auth.SignInResponse, error) {
	ret := _mock.Called(context1, signInRequest)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 *auth.SignInResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.SignInRequest) (*auth.SignInResponse, error)); ok {
		return returnFunc(context1, signInRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.SignInRequest) *auth.SignInResponse); ok {
		r0 = returnFunc(context1, signInRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.SignInResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.SignInRequest) error); ok {
		r1 = returnFunc(context1, signInRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGrpcHandler_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockIGrpcHandler_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - context1 context.Context
//   - signInRequest *auth.SignInRequest
func (_e *MockIGrpcHandler_Expecter) SignIn(context1 interface{}, signInRequest interface{}) *MockIGrpcHandler_SignIn_Call {
	return &MockIGrpcHandler_SignIn_Call{Call: _e.mock.On("SignIn", context1, signInRequest)}
}

func (_c *MockIGrpcHandler_SignIn_Call) Run(run func(context1 context.Context, signInRequest *auth.SignInRequest)) *MockIGrpcHandler_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.SignInRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.SignInRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGrpcHandler_SignIn_Call) Return(signInResponse *auth.SignInResponse, err error) *MockIGrpcHandler_SignIn_Call {
	_c.Call.Return(signInResponse, err)
	return _c
}

func (_c *MockIGrpcHandler_SignIn_Call) RunAndReturn(run func(context1 context.Context, signInRequest *auth.SignInRequest) (*auth.SignInResponse, error)) *MockIGrpcHandler_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignOut provides a mock function for the type MockIGrpcHandler
func (_mock *MockIGrpcHandler) SignOut(context1 context.Context, signOutRequest *auth.SignOutRequest) (*auth.SignOutResponse, error) {
	ret := _mock.Called(context1, signOutRequest)

	if len(ret) == 0 {
		panic("no return value specified for SignOut")
	}

	var r0 *auth.SignOutResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.SignOutRequest) (*auth.SignOutResponse, error)); ok {
		return returnFunc(context1, signOutRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.SignOutRequest) *auth.SignOutResponse); ok {
		r0 = returnFunc(context1, signOutRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.SignOutResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.SignOutRequest) error); ok {
		r1 = returnFunc(context1, signOutRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGrpcHandler_SignOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignOut'
type MockIGrpcHandler_SignOut_Call struct {
	*mock.Call
}

// SignOut is a helper method to define mock.On call
//   - context1 context.Context
//   - signOutRequest *auth.SignOutRequest
func (_e *MockIGrpcHandler_Expecter) SignOut(context1 interface{}, signOutRequest interface{}) *MockIGrpcHandler_SignOut_Call {
	return &MockIGrpcHandler_SignOut_Call{Call: _e.mock.On("SignOut", context1, signOutRequest)}
}

func (_c *MockIGrpcHandler_SignOut_Call) Run(run func(context1 context.Context, signOutRequest *auth.SignOutRequest)) *MockIGrpcHandler_SignOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.SignOutRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.SignOutRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGrpcHandler_SignOut_Call) Return(signOutResponse *auth.SignOutResponse, err error) *MockIGrpcHandler_SignOut_Call {
	_c.Call.Return(signOutResponse, err)
	return _c
}

func (_c *MockIGrpcHandler_SignOut_Call) RunAndReturn(run func(context1 context.Context, signOutRequest *auth.SignOutRequest) (*auth.SignOutResponse, error)) *MockIGrpcHandler_SignOut_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockIGrpcHandler
func (_mock *MockIGrpcHandler) SignUp(context1 context.Context, signUpRequest *auth.SignUpRequest) (*auth.SignUpResponse, error) {
	ret := _mock.Called(context1, signUpRequest)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 *auth.SignUpResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.SignUpRequest) (*auth.SignUpResponse, error)); ok {
		return returnFunc(context1, signUpRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.SignUpRequest) *auth.SignUpResponse); ok {
		r0 = returnFunc(context1, signUpRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.SignUpResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.SignUpRequest) error); ok {
		r1 = returnFunc(context1, signUpRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGrpcHandler_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockIGrpcHandler_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - context1 context.Context
//   - signUpRequest *auth.SignUpRequest
func (_e *MockIGrpcHandler_Expecter) SignUp(context1 interface{}, signUpRequest interface{}) *MockIGrpcHandler_SignUp_Call {
	return &MockIGrpcHandler_SignUp_Call{Call: _e.mock.On("SignUp", context1, signUpRequest)}
}

func (_c *MockIGrpcHandler_SignUp_Call) Run(run func(context1 context.Context, signUpRequest *auth.SignUpRequest)) *MockIGrpcHandler_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.SignUpRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.SignUpRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGrpcHandler_SignUp_Call) Return(signUpResponse *auth.SignUpResponse, err error) *MockIGrpcHandler_SignUp_Call {
	_c.Call.Return(signUpResponse, err)
	return _c
}

func (_c *MockIGrpcHandler_SignUp_Call) RunAndReturn(run func(context1 context.Context, signUpRequest *auth.SignUpRequest) (*auth.SignUpResponse, error)) *MockIGrpcHandler_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedServiceServer provides a mock function for the type MockIGrpcHandler
func (_mock *MockIGrpcHandler) mustEmbedUnimplementedServiceServer() {
	_mock.Called()
	return
}

// MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedServiceServer'
type MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedServiceServer is a helper method to define mock.On call
func (_e *MockIGrpcHandler_Expecter) mustEmbedUnimplementedServiceServer() *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call {
	return &MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedServiceServer")}
}

func (_c *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call) Run(run func()) *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call) Return() *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call) RunAndReturn(run func()) *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockIHttpHandler creates a new instance of MockIHttpHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHttpHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHttpHandler {
	mock := &MockIHttpHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIHttpHandler is an autogenerated mock type for the IHttpHandler type
type MockIHttpHandler struct {
	mock.Mock
}

type MockIHttpHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHttpHandler) EXPECT() *MockIHttpHandler_Expecter {
	return &MockIHttpHandler_Expecter{mock: &_m.Mock}
}

// Me provides a mock function for the type MockIHttpHandler
func (_mock *MockIHttpHandler) Me(c *echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHttpHandler_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockIHttpHandler_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - c *echo.Context
func (_e *MockIHttpHandler_Expecter) Me(c interface{}) *MockIHttpHandler_Me_Call {
	return &MockIHttpHandler_Me_Call{Call: _e.mock.On("Me", c)}
}

func (_c *MockIHttpHandler_Me_Call) Run(run func(c *echo.Context)) *MockIHttpHandler_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Context
		if args[0] != nil {
			arg0 = args[0].(*echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHttpHandler_Me_Call) Return(err error) *MockIHttpHandler_Me_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHttpHandler_Me_Call) RunAndReturn(run func(c *echo.Context) error) *MockIHttpHandler_Me_Call {
	_c.Call.Return(run)
	return _c
}

// SignIn provides a mock function for the type MockIHttpHandler
func (_mock *MockIHttpHandler) SignIn(c *echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHttpHandler_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockIHttpHandler_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - c *echo.Context
func (_e *MockIHttpHandler_Expecter) SignIn(c interface{}) *MockIHttpHandler_SignIn_Call {
	return &MockIHttpHandler_SignIn_Call{Call: _e.mock.On("SignIn", c)}
}

func (_c *MockIHttpHandler_SignIn_Call) Run(run func(c *echo.Context)) *MockIHttpHandler_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Context
		if args[0] != nil {
			arg0 = args[0].(*echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHttpHandler_SignIn_Call) Return(err error) *MockIHttpHandler_SignIn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHttpHandler_SignIn_Call) RunAndReturn(run func(c *echo.Context) error) *MockIHttpHandler_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignOut provides a mock function for the type MockIHttpHandler
func (_mock *MockIHttpHandler) SignOut(c *echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for SignOut")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHttpHandler_SignOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignOut'
type MockIHttpHandler_SignOut_Call struct {
	*mock.Call
}

// SignOut is a helper method to define mock.On call
//   - c *echo.Context
func (_e *MockIHttpHandler_Expecter) SignOut(c interface{}) *MockIHttpHandler_SignOut_Call {
	return &MockIHttpHandler_SignOut_Call{Call: _e.mock.On("SignOut", c)}
}

func (_c *MockIHttpHandler_SignOut_Call) Run(run func(c *echo.Context)) *MockIHttpHandler_SignOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Context
		if args[0] != nil {
			arg0 = args[0].(*echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHttpHandler_SignOut_Call) Return(err error) *MockIHttpHandler_SignOut_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHttpHandler_SignOut_Call) RunAndReturn(run func(c *echo.Context) error) *MockIHttpHandler_SignOut_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockIHttpHandler
func (_mock *MockIHttpHandler) SignUp(c *echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHttpHandler_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockIHttpHandler_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - c *echo.Context
func (_e *MockIHttpHandler_Expecter) SignUp(c interface{}) *MockIHttpHandler_SignUp_Call {
	return &MockIHttpHandler_SignUp_Call{Call: _e.mock.On("SignUp", c)}
}

func (_c *MockIHttpHandler_SignUp_Call) Run(run func(c *echo.Context)) *MockIHttpHandler_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Context
		if args[0] != nil {
			arg0 = args[0].(*echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHttpHandler_SignUp_Call) Return(err error) *MockIHttpHandler_SignUp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHttpHandler_SignUp_Call) RunAndReturn(run func(c *echo.Context) error) *MockIHttpHandler_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUsecase creates a new instance of MockIUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUsecase {
	mock := &MockIUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUsecase is an autogenerated mock type for the IUsecase type
type MockIUsecase struct {
	mock.Mock
}

type MockIUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUsecase) EXPECT() *MockIUsecase_Expecter {
	return &MockIUsecase_Expecter{mock: &_m.Mock}
}

// Me provides a mock function for the type MockIUsecase
func (_mock *MockIUsecase) Me(ctx context.Context) (*MeResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 *MeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*MeResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *MeResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUsecase_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockIUsecase_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIUsecase_Expecter) Me(ctx interface{}) *MockIUsecase_Me_Call {
	return &MockIUsecase_Me_Call{Call: _e.mock.On("Me", ctx)}
}

func (_c *MockIUsecase_Me_Call) Run(run func(ctx context.Context)) *MockIUsecase_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUsecase_Me_Call) Return(meResponse *MeResponse, err error) *MockIUsecase_Me_Call {
	_c.Call.Return(meResponse, err)
	return _c
}

func (_c *MockIUsecase_Me_Call) RunAndReturn(run func(ctx context.Context) (*MeResponse, error)) *MockIUsecase_Me_Call {
	_c.Call.Return(run)
	return _c
}

// SignIn provides a mock function for the type MockIUsecase
func (_mock *MockIUsecase) SignIn(ctx context.Context, req SignInRequest) (*SignInResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 *SignInResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SignInRequest) (*SignInResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, SignInRequest) *SignInResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignInResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, SignInRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUsecase_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockIUsecase_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - ctx context.Context
//   - req SignInRequest
func (_e *MockIUsecase_Expecter) SignIn(ctx interface{}, req interface{}) *MockIUsecase_SignIn_Call {
	return &MockIUsecase_SignIn_Call{Call: _e.mock.On("SignIn", ctx, req)}
}

func (_c *MockIUsecase_SignIn_Call) Run(run func(ctx context.Context, req SignInRequest)) *MockIUsecase_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SignInRequest
		if args[1] != nil {
			arg1 = args[1].(SignInRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUsecase_SignIn_Call) Return(signInResponse *SignInResponse, err error) *MockIUsecase_SignIn_Call {
	_c.Call.Return(signInResponse, err)
	return _c
}

func (_c *MockIUsecase_SignIn_Call) RunAndReturn(run func(ctx context.Context, req SignInRequest) (*SignInResponse, error)) *MockIUsecase_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignOut provides a mock function for the type MockIUsecase
func (_mock *MockIUsecase) SignOut(ctx context.Context, req SignOutRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignOut")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SignOutRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUsecase_SignOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignOut'
type MockIUsecase_SignOut_Call struct {
	*mock.Call
}

// SignOut is a helper method to define mock.On call
//   - ctx context.Context
//   - req SignOutRequest
func (_e *MockIUsecase_Expecter) SignOut(ctx interface{}, req interface{}) *MockIUsecase_SignOut_Call {
	return &MockIUsecase_SignOut_Call{Call: _e.mock.On("SignOut", ctx, req)}
}

func (_c *MockIUsecase_SignOut_Call) Run(run func(ctx context.Context, req SignOutRequest)) *MockIUsecase_SignOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SignOutRequest
		if args[1] != nil {
			arg1 = args[1].(SignOutRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUsecase_SignOut_Call) Return(err error) *MockIUsecase_SignOut_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUsecase_SignOut_Call) RunAndReturn(run func(ctx context.Context, req SignOutRequest) error) *MockIUsecase_SignOut_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockIUsecase
func (_mock *MockIUsecase) SignUp(ctx context.Context, req SignUpRequest) (*SignUpResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 *SignUpResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SignUpRequest) (*SignUpResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, SignUpRequest) *SignUpResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignUpResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, SignUpRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUsecase_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockIUsecase_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - req SignUpRequest
func (_e *MockIUsecase_Expecter) SignUp(ctx interface{}, req interface{}) *MockIUsecase_SignUp_Call {
	return &MockIUsecase_SignUp_Call{Call: _e.mock.On("SignUp", ctx, req)}
}

func (_c *MockIUsecase_SignUp_Call) Run(run func(ctx context.Context, req SignUpRequest)) *MockIUsecase_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SignUpRequest
		if args[1] != nil {
			arg1 = args[1].(SignUpRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUsecase_SignUp_Call) Return(signUpResponse *SignUpResponse, err error) *MockIUsecase_SignUp_Call {
	_c.Call.Return(signUpResponse, err)
	return _c
}

func (_c *MockIUsecase_SignUp_Call) RunAndReturn(run func(ctx context.Context, req SignUpRequest) (*SignUpResponse, error)) *MockIUsecase_SignUp_Call {
	_c.Call.Return(run)
	return _c
}
