// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
	mock "github.com/stretchr/testify/mock"
	"github.com/uptrace/bun"
)

// NewMockIDB creates a new instance of MockIDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDB {
	mock := &MockIDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIDB is an autogenerated mock type for the IDB type
type MockIDB struct {
	mock.Mock
}

type MockIDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDB) EXPECT() *MockIDB_Expecter {
	return &MockIDB_Expecter{mock: &_m.Mock}
}

// DB provides a mock function for the type MockIDB
func (_mock *MockIDB) DB(ctx context.Context) bun.IDB {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 bun.IDB
	if returnFunc, ok := ret.Get(0).(func(context.Context) bun.IDB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bun.IDB)
		}
	}
	return r0
}

// MockIDB_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockIDB_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDB_Expecter) DB(ctx interface{}) *MockIDB_DB_Call {
	return &MockIDB_DB_Call{Call: _e.mock.On("DB", ctx)}
}

func (_c *MockIDB_DB_Call) Run(run func(ctx context.Context)) *MockIDB_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDB_DB_Call) Return(iDB bun.IDB) *MockIDB_DB_Call {
	_c.Call.Return(iDB)
	return _c
}

func (_c *MockIDB_DB_Call) RunAndReturn(run func(ctx context.Context) bun.IDB) *MockIDB_DB_Call {
	_c.Call.Return(run)
	return _c
}

// PgxPool provides a mock function for the type MockIDB
func (_mock *MockIDB) PgxPool(ctx context.Context) *pgxpool.Pool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PgxPool")
	}

	var r0 *pgxpool.Pool
	if returnFunc, ok := ret.Get(0).(func(context.Context) *pgxpool.Pool); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxpool.Pool)
		}
	}
	return r0
}

// MockIDB_PgxPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PgxPool'
type MockIDB_PgxPool_Call struct {
	*mock.Call
}

// PgxPool is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDB_Expecter) PgxPool(ctx interface{}) *MockIDB_PgxPool_Call {
	return &MockIDB_PgxPool_Call{Call: _e.mock.On("PgxPool", ctx)}
}

func (_c *MockIDB_PgxPool_Call) Run(run func(ctx context.Context)) *MockIDB_PgxPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDB_PgxPool_Call) Return(pool *pgxpool.Pool) *MockIDB_PgxPool_Call {
	_c.Call.Return(pool)
	return _c
}

func (_c *MockIDB_PgxPool_Call) RunAndReturn(run func(ctx context.Context) *pgxpool.Pool) *MockIDB_PgxPool_Call {
	_c.Call.Return(run)
	return _c
}
