// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rabbitmq

import (
	"context"

	"github.com/anonychun/bibit/internal/consumer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIBroker creates a new instance of MockIBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBroker {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockIBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockIBroker is an autogenerated mock type for the IBroker type
type MockIBroker struct {
	mock.Mock
}

type MockIBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBroker) EXPECT() *MockIBroker_Expecter {
	return &MockIBroker_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockIBroker
func (_mock *MockIBroker) Start(ctx context.Context, routes []consumer.Route) error {
	ret := _mock.Called(ctx, routes)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []consumer.Route) error); ok {
		r0 = returnFunc(ctx, routes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBroker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIBroker_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - routes []consumer.Route
func (_e *MockIBroker_Expecter) Start(ctx any, routes any) *MockIBroker_Start_Call {
	return &MockIBroker_Start_Call{Call: _e.mock.On("Start", ctx, routes)}
}

func (_c *MockIBroker_Start_Call) Run(run func(ctx context.Context, routes []consumer.Route)) *MockIBroker_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []consumer.Route
		if args[1] != nil {
			arg1 = args[1].([]consumer.Route)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBroker_Start_Call) Return(err error) *MockIBroker_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBroker_Start_Call) RunAndReturn(run func(ctx context.Context, routes []consumer.Route) error) *MockIBroker_Start_Call {
	_c.Call.Return(run)
	return _c
}
