// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package s3

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIStorage creates a new instance of MockIStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStorage {
	mock := &MockIStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStorage is an autogenerated mock type for the IStorage type
type MockIStorage struct {
	mock.Mock
}

type MockIStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStorage) EXPECT() *MockIStorage_Expecter {
	return &MockIStorage_Expecter{mock: &_m.Mock}
}

// GetObject provides a mock function for the type MockIStorage
func (_mock *MockIStorage) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *s3.GetObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) (*s3.GetObjectOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) *s3.GetObjectOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStorage_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockIStorage_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.GetObjectInput
//   - optFns ...func(*s3.Options)
func (_e *MockIStorage_Expecter) GetObject(ctx interface{}, params interface{}, optFns ...interface{}) *MockIStorage_GetObject_Call {
	return &MockIStorage_GetObject_Call{Call: _e.mock.On("GetObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockIStorage_GetObject_Call) Run(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options))) *MockIStorage_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.GetObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.GetObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIStorage_GetObject_Call) Return(getObjectOutput *s3.GetObjectOutput, err error) *MockIStorage_GetObject_Call {
	_c.Call.Return(getObjectOutput, err)
	return _c
}

func (_c *MockIStorage_GetObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error)) *MockIStorage_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// PresignGetObject provides a mock function for the type MockIStorage
func (_mock *MockIStorage) PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PresignGetObject")
	}

	var r0 *v4.PresignedHTTPRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) *v4.PresignedHTTPRequest); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v4.PresignedHTTPRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStorage_PresignGetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGetObject'
type MockIStorage_PresignGetObject_Call struct {
	*mock.Call
}

// PresignGetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.GetObjectInput
//   - optFns ...func(*s3.PresignOptions)
func (_e *MockIStorage_Expecter) PresignGetObject(ctx interface{}, params interface{}, optFns ...interface{}) *MockIStorage_PresignGetObject_Call {
	return &MockIStorage_PresignGetObject_Call{Call: _e.mock.On("PresignGetObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockIStorage_PresignGetObject_Call) Run(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions))) *MockIStorage_PresignGetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.GetObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.GetObjectInput)
		}
		var arg2 []func(*s3.PresignOptions)
		var variadicArgs []func(*s3.PresignOptions)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.PresignOptions))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIStorage_PresignGetObject_Call) Return(presignedHTTPRequest *v4.PresignedHTTPRequest, err error) *MockIStorage_PresignGetObject_Call {
	_c.Call.Return(presignedHTTPRequest, err)
	return _c
}

func (_c *MockIStorage_PresignGetObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *MockIStorage_PresignGetObject_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type MockIStorage
func (_mock *MockIStorage) PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *s3.PutObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) *s3.PutObjectOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.PutObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStorage_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockIStorage_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.PutObjectInput
//   - optFns ...func(*s3.Options)
func (_e *MockIStorage_Expecter) PutObject(ctx interface{}, params interface{}, optFns ...interface{}) *MockIStorage_PutObject_Call {
	return &MockIStorage_PutObject_Call{Call: _e.mock.On("PutObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockIStorage_PutObject_Call) Run(run func(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options))) *MockIStorage_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.PutObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.PutObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIStorage_PutObject_Call) Return(putObjectOutput *s3.PutObjectOutput, err error) *MockIStorage_PutObject_Call {
	_c.Call.Return(putObjectOutput, err)
	return _c
}

func (_c *MockIStorage_PutObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error)) *MockIStorage_PutObject_Call {
	_c.Call.Return(run)
	return _c
}
