// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIGrpcServer creates a new instance of MockIGrpcServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIGrpcServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIGrpcServer {
	mock := &MockIGrpcServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIGrpcServer is an autogenerated mock type for the IGrpcServer type
type MockIGrpcServer struct {
	mock.Mock
}

type MockIGrpcServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIGrpcServer) EXPECT() *MockIGrpcServer_Expecter {
	return &MockIGrpcServer_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockIGrpcServer
func (_mock *MockIGrpcServer) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIGrpcServer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIGrpcServer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIGrpcServer_Expecter) Start(ctx interface{}) *MockIGrpcServer_Start_Call {
	return &MockIGrpcServer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockIGrpcServer_Start_Call) Run(run func(ctx context.Context)) *MockIGrpcServer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGrpcServer_Start_Call) Return(err error) *MockIGrpcServer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIGrpcServer_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockIGrpcServer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIHttpServer creates a new instance of MockIHttpServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHttpServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHttpServer {
	mock := &MockIHttpServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIHttpServer is an autogenerated mock type for the IHttpServer type
type MockIHttpServer struct {
	mock.Mock
}

type MockIHttpServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHttpServer) EXPECT() *MockIHttpServer_Expecter {
	return &MockIHttpServer_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockIHttpServer
func (_mock *MockIHttpServer) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHttpServer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIHttpServer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIHttpServer_Expecter) Start(ctx interface{}) *MockIHttpServer_Start_Call {
	return &MockIHttpServer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockIHttpServer_Start_Call) Run(run func(ctx context.Context)) *MockIHttpServer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHttpServer_Start_Call) Return(err error) *MockIHttpServer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHttpServer_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockIHttpServer_Start_Call {
	_c.Call.Return(run)
	return _c
}
