// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package river

import (
	"github.com/jackc/pgx/v5"
	"github.com/riverqueue/river"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIClient creates a new instance of MockIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIClient {
	mock := &MockIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIClient is an autogenerated mock type for the IClient type
type MockIClient struct {
	mock.Mock
}

type MockIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIClient) EXPECT() *MockIClient_Expecter {
	return &MockIClient_Expecter{mock: &_m.Mock}
}

// Client provides a mock function for the type MockIClient
func (_mock *MockIClient) Client() *river.Client[pgx.Tx] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Client")
	}

	var r0 *river.Client[pgx.Tx]
	if returnFunc, ok := ret.Get(0).(func() *river.Client[pgx.Tx]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*river.Client[pgx.Tx])
		}
	}
	return r0
}

// MockIClient_Client_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Client'
type MockIClient_Client_Call struct {
	*mock.Call
}

// Client is a helper method to define mock.On call
func (_e *MockIClient_Expecter) Client() *MockIClient_Client_Call {
	return &MockIClient_Client_Call{Call: _e.mock.On("Client")}
}

func (_c *MockIClient_Client_Call) Run(run func()) *MockIClient_Client_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIClient_Client_Call) Return(client *river.Client[pgx.Tx]) *MockIClient_Client_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockIClient_Client_Call) RunAndReturn(run func() *river.Client[pgx.Tx]) *MockIClient_Client_Call {
	_c.Call.Return(run)
	return _c
}

// Workers provides a mock function for the type MockIClient
func (_mock *MockIClient) Workers() *river.Workers {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Workers")
	}

	var r0 *river.Workers
	if returnFunc, ok := ret.Get(0).(func() *river.Workers); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*river.Workers)
		}
	}
	return r0
}

// MockIClient_Workers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Workers'
type MockIClient_Workers_Call struct {
	*mock.Call
}

// Workers is a helper method to define mock.On call
func (_e *MockIClient_Expecter) Workers() *MockIClient_Workers_Call {
	return &MockIClient_Workers_Call{Call: _e.mock.On("Workers")}
}

func (_c *MockIClient_Workers_Call) Run(run func()) *MockIClient_Workers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIClient_Workers_Call) Return(workers *river.Workers) *MockIClient_Workers_Call {
	_c.Call.Return(workers)
	return _c
}

func (_c *MockIClient_Workers_Call) RunAndReturn(run func() *river.Workers) *MockIClient_Workers_Call {
	_c.Call.Return(run)
	return _c
}
