// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package consumer

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIConsumer creates a new instance of MockIConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIConsumer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockIConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockIConsumer is an autogenerated mock type for the IConsumer type
type MockIConsumer struct {
	mock.Mock
}

type MockIConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIConsumer) EXPECT() *MockIConsumer_Expecter {
	return &MockIConsumer_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type MockIConsumer
func (_mock *MockIConsumer) Consume(ctx context.Context, messages []*Message) error {
	ret := _mock.Called(ctx, messages)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*Message) error); ok {
		r0 = returnFunc(ctx, messages)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIConsumer_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockIConsumer_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []*Message
func (_e *MockIConsumer_Expecter) Consume(ctx any, messages any) *MockIConsumer_Consume_Call {
	return &MockIConsumer_Consume_Call{Call: _e.mock.On("Consume", ctx, messages)}
}

func (_c *MockIConsumer_Consume_Call) Run(run func(ctx context.Context, messages []*Message)) *MockIConsumer_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*Message
		if args[1] != nil {
			arg1 = args[1].([]*Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIConsumer_Consume_Call) Return(err error) *MockIConsumer_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIConsumer_Consume_Call) RunAndReturn(run func(ctx context.Context, messages []*Message) error) *MockIConsumer_Consume_Call {
	_c.Call.Return(run)
	return _c
}
