// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package manager

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIDB creates a new instance of MockIDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDB {
	mock := &MockIDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIDB is an autogenerated mock type for the IDB type
type MockIDB struct {
	mock.Mock
}

type MockIDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDB) EXPECT() *MockIDB_Expecter {
	return &MockIDB_Expecter{mock: &_m.Mock}
}

// CreateDatabase provides a mock function for the type MockIDB
func (_mock *MockIDB) CreateDatabase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateDatabase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDB_CreateDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDatabase'
type MockIDB_CreateDatabase_Call struct {
	*mock.Call
}

// CreateDatabase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDB_Expecter) CreateDatabase(ctx interface{}) *MockIDB_CreateDatabase_Call {
	return &MockIDB_CreateDatabase_Call{Call: _e.mock.On("CreateDatabase", ctx)}
}

func (_c *MockIDB_CreateDatabase_Call) Run(run func(ctx context.Context)) *MockIDB_CreateDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDB_CreateDatabase_Call) Return(err error) *MockIDB_CreateDatabase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDB_CreateDatabase_Call) RunAndReturn(run func(ctx context.Context) error) *MockIDB_CreateDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// DropDatabase provides a mock function for the type MockIDB
func (_mock *MockIDB) DropDatabase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DropDatabase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDB_DropDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropDatabase'
type MockIDB_DropDatabase_Call struct {
	*mock.Call
}

// DropDatabase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDB_Expecter) DropDatabase(ctx interface{}) *MockIDB_DropDatabase_Call {
	return &MockIDB_DropDatabase_Call{Call: _e.mock.On("DropDatabase", ctx)}
}

func (_c *MockIDB_DropDatabase_Call) Run(run func(ctx context.Context)) *MockIDB_DropDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDB_DropDatabase_Call) Return(err error) *MockIDB_DropDatabase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDB_DropDatabase_Call) RunAndReturn(run func(ctx context.Context) error) *MockIDB_DropDatabase_Call {
	_c.Call.Return(run)
	return _c
}
