// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validation

import (
	"github.com/anonychun/bibit/internal/api"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIValidator creates a new instance of MockIValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIValidator {
	mock := &MockIValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIValidator is an autogenerated mock type for the IValidator type
type MockIValidator struct {
	mock.Mock
}

type MockIValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIValidator) EXPECT() *MockIValidator_Expecter {
	return &MockIValidator_Expecter{mock: &_m.Mock}
}

// Struct provides a mock function for the type MockIValidator
func (_mock *MockIValidator) Struct(s any) api.ValidationError {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Struct")
	}

	var r0 api.ValidationError
	if returnFunc, ok := ret.Get(0).(func(any) api.ValidationError); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.ValidationError)
		}
	}
	return r0
}

// MockIValidator_Struct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Struct'
type MockIValidator_Struct_Call struct {
	*mock.Call
}

// Struct is a helper method to define mock.On call
//   - s any
func (_e *MockIValidator_Expecter) Struct(s interface{}) *MockIValidator_Struct_Call {
	return &MockIValidator_Struct_Call{Call: _e.mock.On("Struct", s)}
}

func (_c *MockIValidator_Struct_Call) Run(run func(s any)) *MockIValidator_Struct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIValidator_Struct_Call) Return(validationError api.ValidationError) *MockIValidator_Struct_Call {
	_c.Call.Return(validationError)
	return _c
}

func (_c *MockIValidator_Struct_Call) RunAndReturn(run func(s any) api.ValidationError) *MockIValidator_Struct_Call {
	_c.Call.Return(run)
	return _c
}
