// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"github.com/labstack/echo/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIMiddleware creates a new instance of MockIMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMiddleware {
	mock := &MockIMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIMiddleware is an autogenerated mock type for the IMiddleware type
type MockIMiddleware struct {
	mock.Mock
}

type MockIMiddleware_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMiddleware) EXPECT() *MockIMiddleware_Expecter {
	return &MockIMiddleware_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function for the type MockIMiddleware
func (_mock *MockIMiddleware) AuthenticateUser(next echo.HandlerFunc) echo.HandlerFunc {
	ret := _mock.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 echo.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func(echo.HandlerFunc) echo.HandlerFunc); ok {
		r0 = returnFunc(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}
	return r0
}

// MockIMiddleware_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type MockIMiddleware_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - next echo.HandlerFunc
func (_e *MockIMiddleware_Expecter) AuthenticateUser(next interface{}) *MockIMiddleware_AuthenticateUser_Call {
	return &MockIMiddleware_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", next)}
}

func (_c *MockIMiddleware_AuthenticateUser_Call) Run(run func(next echo.HandlerFunc)) *MockIMiddleware_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.HandlerFunc
		if args[0] != nil {
			arg0 = args[0].(echo.HandlerFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIMiddleware_AuthenticateUser_Call) Return(handlerFunc echo.HandlerFunc) *MockIMiddleware_AuthenticateUser_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockIMiddleware_AuthenticateUser_Call) RunAndReturn(run func(next echo.HandlerFunc) echo.HandlerFunc) *MockIMiddleware_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}
