// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: health/service.proto

package health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpRequest) Reset() {
	*x = UpRequest{}
	mi := &file_health_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpRequest) ProtoMessage() {}

func (x *UpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpRequest.ProtoReflect.Descriptor instead.
func (*UpRequest) Descriptor() ([]byte, []int) {
	return file_health_service_proto_rawDescGZIP(), []int{0}
}

type UpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpResponse) Reset() {
	*x = UpResponse{}
	mi := &file_health_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpResponse) ProtoMessage() {}

func (x *UpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpResponse.ProtoReflect.Descriptor instead.
func (*UpResponse) Descriptor() ([]byte, []int) {
	return file_health_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_health_service_proto protoreflect.FileDescriptor

const file_health_service_proto_rawDesc = "" +
	"\n" +
	"\x14health/service.proto\x12\x06health\"\v\n" +
	"\tUpRequest\"$\n" +
	"\n" +
	"UpResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status26\n" +
	"\aService\x12+\n" +
	"\x02Up\x12\x11.health.UpRequest\x1a\x12.health.UpResponseB*Z(github.com/anonychun/bibit/pkg/pb/healthb\x06proto3"

var (
	file_health_service_proto_rawDescOnce sync.Once
	file_health_service_proto_rawDescData []byte
)

func file_health_service_proto_rawDescGZIP() []byte {
	file_health_service_proto_rawDescOnce.Do(func() {
		file_health_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_service_proto_rawDesc), len(file_health_service_proto_rawDesc)))
	})
	return file_health_service_proto_rawDescData
}

var file_health_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_health_service_proto_goTypes = []any{
	(*UpRequest)(nil),  // 0: health.UpRequest
	(*UpResponse)(nil), // 1: health.UpResponse
}
var file_health_service_proto_depIdxs = []int32{
	0, // 0: health.Service.Up:input_type -> health.UpRequest
	1, // 1: health.Service.Up:output_type -> health.UpResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_health_service_proto_init() }
func file_health_service_proto_init() {
	if File_health_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_service_proto_rawDesc), len(file_health_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_service_proto_goTypes,
		DependencyIndexes: file_health_service_proto_depIdxs,
		MessageInfos:      file_health_service_proto_msgTypes,
	}.Build()
	File_health_service_proto = out.File
	file_health_service_proto_goTypes = nil
	file_health_service_proto_depIdxs = nil
}
