// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logger

import (
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewMockILogger creates a new instance of MockILogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILogger {
	mock := &MockILogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockILogger is an autogenerated mock type for the ILogger type
type MockILogger struct {
	mock.Mock
}

type MockILogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockILogger) EXPECT() *MockILogger_Expecter {
	return &MockILogger_Expecter{mock: &_m.Mock}
}

// Log provides a mock function for the type MockILogger
func (_mock *MockILogger) Log() *slog.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 *slog.Logger
	if returnFunc, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}
	return r0
}

// MockILogger_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockILogger_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
func (_e *MockILogger_Expecter) Log() *MockILogger_Log_Call {
	return &MockILogger_Log_Call{Call: _e.mock.On("Log")}
}

func (_c *MockILogger_Log_Call) Run(run func()) *MockILogger_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockILogger_Log_Call) Return(logger *slog.Logger) *MockILogger_Log_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockILogger_Log_Call) RunAndReturn(run func() *slog.Logger) *MockILogger_Log_Call {
	_c.Call.Return(run)
	return _c
}
