// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package o11y

import (
	"log/slog"

	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

// NewMockIO11y creates a new instance of MockIO11y. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIO11y(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIO11y {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockIO11y{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockIO11y is an autogenerated mock type for the IO11y type
type MockIO11y struct {
	mock.Mock
}

type MockIO11y_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIO11y) EXPECT() *MockIO11y_Expecter {
	return &MockIO11y_Expecter{mock: &_m.Mock}
}

// Logger provides a mock function for the type MockIO11y
func (_mock *MockIO11y) Logger() *slog.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *slog.Logger
	if returnFunc, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}
	return r0
}

// MockIO11y_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockIO11y_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockIO11y_Expecter) Logger() *MockIO11y_Logger_Call {
	return &MockIO11y_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockIO11y_Logger_Call) Run(run func()) *MockIO11y_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIO11y_Logger_Call) Return(logger *slog.Logger) *MockIO11y_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockIO11y_Logger_Call) RunAndReturn(run func() *slog.Logger) *MockIO11y_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Meter provides a mock function for the type MockIO11y
func (_mock *MockIO11y) Meter() metric.Meter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Meter")
	}

	var r0 metric.Meter
	if returnFunc, ok := ret.Get(0).(func() metric.Meter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metric.Meter)
		}
	}
	return r0
}

// MockIO11y_Meter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Meter'
type MockIO11y_Meter_Call struct {
	*mock.Call
}

// Meter is a helper method to define mock.On call
func (_e *MockIO11y_Expecter) Meter() *MockIO11y_Meter_Call {
	return &MockIO11y_Meter_Call{Call: _e.mock.On("Meter")}
}

func (_c *MockIO11y_Meter_Call) Run(run func()) *MockIO11y_Meter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIO11y_Meter_Call) Return(meter metric.Meter) *MockIO11y_Meter_Call {
	_c.Call.Return(meter)
	return _c
}

func (_c *MockIO11y_Meter_Call) RunAndReturn(run func() metric.Meter) *MockIO11y_Meter_Call {
	_c.Call.Return(run)
	return _c
}

// Tracer provides a mock function for the type MockIO11y
func (_mock *MockIO11y) Tracer() trace.Tracer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tracer")
	}

	var r0 trace.Tracer
	if returnFunc, ok := ret.Get(0).(func() trace.Tracer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(trace.Tracer)
		}
	}
	return r0
}

// MockIO11y_Tracer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tracer'
type MockIO11y_Tracer_Call struct {
	*mock.Call
}

// Tracer is a helper method to define mock.On call
func (_e *MockIO11y_Expecter) Tracer() *MockIO11y_Tracer_Call {
	return &MockIO11y_Tracer_Call{Call: _e.mock.On("Tracer")}
}

func (_c *MockIO11y_Tracer_Call) Run(run func()) *MockIO11y_Tracer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIO11y_Tracer_Call) Return(tracer trace.Tracer) *MockIO11y_Tracer_Call {
	_c.Call.Return(tracer)
	return _c
}

func (_c *MockIO11y_Tracer_Call) RunAndReturn(run func() trace.Tracer) *MockIO11y_Tracer_Call {
	_c.Call.Return(run)
	return _c
}
