// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIWorker creates a new instance of MockIWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIWorker {
	mock := &MockIWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIWorker is an autogenerated mock type for the IWorker type
type MockIWorker struct {
	mock.Mock
}

type MockIWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIWorker) EXPECT() *MockIWorker_Expecter {
	return &MockIWorker_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockIWorker
func (_mock *MockIWorker) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIWorker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIWorker_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIWorker_Expecter) Start(ctx interface{}) *MockIWorker_Start_Call {
	return &MockIWorker_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockIWorker_Start_Call) Run(run func(ctx context.Context)) *MockIWorker_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIWorker_Start_Call) Return(err error) *MockIWorker_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIWorker_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockIWorker_Start_Call {
	_c.Call.Return(run)
	return _c
}
