// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package health

import (
	"context"

	"github.com/anonychun/bibit/pkg/pb/health"
	"github.com/labstack/echo/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIGrpcHandler creates a new instance of MockIGrpcHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIGrpcHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIGrpcHandler {
	mock := &MockIGrpcHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIGrpcHandler is an autogenerated mock type for the IGrpcHandler type
type MockIGrpcHandler struct {
	mock.Mock
}

type MockIGrpcHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIGrpcHandler) EXPECT() *MockIGrpcHandler_Expecter {
	return &MockIGrpcHandler_Expecter{mock: &_m.Mock}
}

// Up provides a mock function for the type MockIGrpcHandler
func (_mock *MockIGrpcHandler) Up(context1 context.Context, upRequest *health.UpRequest) (*health.UpResponse, error) {
	ret := _mock.Called(context1, upRequest)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 *health.UpResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *health.UpRequest) (*health.UpResponse, error)); ok {
		return returnFunc(context1, upRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *health.UpRequest) *health.UpResponse); ok {
		r0 = returnFunc(context1, upRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.UpResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *health.UpRequest) error); ok {
		r1 = returnFunc(context1, upRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGrpcHandler_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockIGrpcHandler_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - context1 context.Context
//   - upRequest *health.UpRequest
func (_e *MockIGrpcHandler_Expecter) Up(context1 any, upRequest any) *MockIGrpcHandler_Up_Call {
	return &MockIGrpcHandler_Up_Call{Call: _e.mock.On("Up", context1, upRequest)}
}

func (_c *MockIGrpcHandler_Up_Call) Run(run func(context1 context.Context, upRequest *health.UpRequest)) *MockIGrpcHandler_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *health.UpRequest
		if args[1] != nil {
			arg1 = args[1].(*health.UpRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGrpcHandler_Up_Call) Return(upResponse *health.UpResponse, err error) *MockIGrpcHandler_Up_Call {
	_c.Call.Return(upResponse, err)
	return _c
}

func (_c *MockIGrpcHandler_Up_Call) RunAndReturn(run func(context1 context.Context, upRequest *health.UpRequest) (*health.UpResponse, error)) *MockIGrpcHandler_Up_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedServiceServer provides a mock function for the type MockIGrpcHandler
func (_mock *MockIGrpcHandler) mustEmbedUnimplementedServiceServer() {
	_mock.Called()
	return
}

// MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedServiceServer'
type MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedServiceServer is a helper method to define mock.On call
func (_e *MockIGrpcHandler_Expecter) mustEmbedUnimplementedServiceServer() *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call {
	return &MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedServiceServer")}
}

func (_c *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call) Run(run func()) *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call) Return() *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call) RunAndReturn(run func()) *MockIGrpcHandler_mustEmbedUnimplementedServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockIHttpHandler creates a new instance of MockIHttpHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHttpHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHttpHandler {
	mock := &MockIHttpHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIHttpHandler is an autogenerated mock type for the IHttpHandler type
type MockIHttpHandler struct {
	mock.Mock
}

type MockIHttpHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHttpHandler) EXPECT() *MockIHttpHandler_Expecter {
	return &MockIHttpHandler_Expecter{mock: &_m.Mock}
}

// Up provides a mock function for the type MockIHttpHandler
func (_mock *MockIHttpHandler) Up(c *echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHttpHandler_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockIHttpHandler_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - c *echo.Context
func (_e *MockIHttpHandler_Expecter) Up(c any) *MockIHttpHandler_Up_Call {
	return &MockIHttpHandler_Up_Call{Call: _e.mock.On("Up", c)}
}

func (_c *MockIHttpHandler_Up_Call) Run(run func(c *echo.Context)) *MockIHttpHandler_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Context
		if args[0] != nil {
			arg0 = args[0].(*echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHttpHandler_Up_Call) Return(err error) *MockIHttpHandler_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHttpHandler_Up_Call) RunAndReturn(run func(c *echo.Context) error) *MockIHttpHandler_Up_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUsecase creates a new instance of MockIUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUsecase {
	mock := &MockIUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUsecase is an autogenerated mock type for the IUsecase type
type MockIUsecase struct {
	mock.Mock
}

type MockIUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUsecase) EXPECT() *MockIUsecase_Expecter {
	return &MockIUsecase_Expecter{mock: &_m.Mock}
}

// Up provides a mock function for the type MockIUsecase
func (_mock *MockIUsecase) Up() (*UpResponse, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 *UpResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*UpResponse, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *UpResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UpResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUsecase_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockIUsecase_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
func (_e *MockIUsecase_Expecter) Up() *MockIUsecase_Up_Call {
	return &MockIUsecase_Up_Call{Call: _e.mock.On("Up")}
}

func (_c *MockIUsecase_Up_Call) Run(run func()) *MockIUsecase_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIUsecase_Up_Call) Return(upResponse *UpResponse, err error) *MockIUsecase_Up_Call {
	_c.Call.Return(upResponse, err)
	return _c
}

func (_c *MockIUsecase_Up_Call) RunAndReturn(run func() (*UpResponse, error)) *MockIUsecase_Up_Call {
	_c.Call.Return(run)
	return _c
}
