// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_session

import (
	"context"

	"github.com/anonychun/bibit/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Create(ctx context.Context, userSession *entity.UserSession) error {
	ret := _mock.Called(ctx, userSession)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.UserSession) error); ok {
		r0 = returnFunc(ctx, userSession)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userSession *entity.UserSession
func (_e *MockIRepository_Expecter) Create(ctx interface{}, userSession interface{}) *MockIRepository_Create_Call {
	return &MockIRepository_Create_Call{Call: _e.mock.On("Create", ctx, userSession)}
}

func (_c *MockIRepository_Create_Call) Run(run func(ctx context.Context, userSession *entity.UserSession)) *MockIRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.UserSession
		if args[1] != nil {
			arg1 = args[1].(*entity.UserSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_Create_Call) Return(err error) *MockIRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userSession *entity.UserSession) error) *MockIRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByToken provides a mock function for the type MockIRepository
func (_mock *MockIRepository) DeleteByToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_DeleteByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByToken'
type MockIRepository_DeleteByToken_Call struct {
	*mock.Call
}

// DeleteByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockIRepository_Expecter) DeleteByToken(ctx interface{}, token interface{}) *MockIRepository_DeleteByToken_Call {
	return &MockIRepository_DeleteByToken_Call{Call: _e.mock.On("DeleteByToken", ctx, token)}
}

func (_c *MockIRepository_DeleteByToken_Call) Run(run func(ctx context.Context, token string)) *MockIRepository_DeleteByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_DeleteByToken_Call) Return(err error) *MockIRepository_DeleteByToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_DeleteByToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockIRepository_DeleteByToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FindByToken(ctx context.Context, token string) (*entity.UserSession, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *entity.UserSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.UserSession, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.UserSession); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockIRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockIRepository_Expecter) FindByToken(ctx interface{}, token interface{}) *MockIRepository_FindByToken_Call {
	return &MockIRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *MockIRepository_FindByToken_Call) Run(run func(ctx context.Context, token string)) *MockIRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_FindByToken_Call) Return(userSession *entity.UserSession, err error) *MockIRepository_FindByToken_Call {
	_c.Call.Return(userSession, err)
	return _c
}

func (_c *MockIRepository_FindByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*entity.UserSession, error)) *MockIRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}
