// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"

	"github.com/anonychun/bibit/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Create(ctx context.Context, user *entity.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockIRepository_Expecter) Create(ctx interface{}, user interface{}) *MockIRepository_Create_Call {
	return &MockIRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockIRepository_Create_Call) Run(run func(ctx context.Context, user *entity.User)) *MockIRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_Create_Call) Return(err error) *MockIRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) error) *MockIRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmailAddress provides a mock function for the type MockIRepository
func (_mock *MockIRepository) ExistsByEmailAddress(ctx context.Context, emailAddress string) (bool, error) {
	ret := _mock.Called(ctx, emailAddress)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmailAddress")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, emailAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, emailAddress)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, emailAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_ExistsByEmailAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmailAddress'
type MockIRepository_ExistsByEmailAddress_Call struct {
	*mock.Call
}

// ExistsByEmailAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - emailAddress string
func (_e *MockIRepository_Expecter) ExistsByEmailAddress(ctx interface{}, emailAddress interface{}) *MockIRepository_ExistsByEmailAddress_Call {
	return &MockIRepository_ExistsByEmailAddress_Call{Call: _e.mock.On("ExistsByEmailAddress", ctx, emailAddress)}
}

func (_c *MockIRepository_ExistsByEmailAddress_Call) Run(run func(ctx context.Context, emailAddress string)) *MockIRepository_ExistsByEmailAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_ExistsByEmailAddress_Call) Return(b bool, err error) *MockIRepository_ExistsByEmailAddress_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIRepository_ExistsByEmailAddress_Call) RunAndReturn(run func(ctx context.Context, emailAddress string) (bool, error)) *MockIRepository_ExistsByEmailAddress_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmailAddress provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FindByEmailAddress(ctx context.Context, emailAddress string) (*entity.User, error) {
	ret := _mock.Called(ctx, emailAddress)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmailAddress")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, emailAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, emailAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, emailAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_FindByEmailAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmailAddress'
type MockIRepository_FindByEmailAddress_Call struct {
	*mock.Call
}

// FindByEmailAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - emailAddress string
func (_e *MockIRepository_Expecter) FindByEmailAddress(ctx interface{}, emailAddress interface{}) *MockIRepository_FindByEmailAddress_Call {
	return &MockIRepository_FindByEmailAddress_Call{Call: _e.mock.On("FindByEmailAddress", ctx, emailAddress)}
}

func (_c *MockIRepository_FindByEmailAddress_Call) Run(run func(ctx context.Context, emailAddress string)) *MockIRepository_FindByEmailAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_FindByEmailAddress_Call) Return(user *entity.User, err error) *MockIRepository_FindByEmailAddress_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIRepository_FindByEmailAddress_Call) RunAndReturn(run func(ctx context.Context, emailAddress string) (*entity.User, error)) *MockIRepository_FindByEmailAddress_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FindById(ctx context.Context, id string) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockIRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIRepository_Expecter) FindById(ctx interface{}, id interface{}) *MockIRepository_FindById_Call {
	return &MockIRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, id)}
}

func (_c *MockIRepository_FindById_Call) Run(run func(ctx context.Context, id string)) *MockIRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_FindById_Call) Return(user *entity.User, err error) *MockIRepository_FindById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIRepository_FindById_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.User, error)) *MockIRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}
