// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package observability

import (
	"log/slog"

	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

// NewMockIObservability creates a new instance of MockIObservability. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIObservability(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIObservability {
	mock := &MockIObservability{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIObservability is an autogenerated mock type for the IObservability type
type MockIObservability struct {
	mock.Mock
}

type MockIObservability_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIObservability) EXPECT() *MockIObservability_Expecter {
	return &MockIObservability_Expecter{mock: &_m.Mock}
}

// Logger provides a mock function for the type MockIObservability
func (_mock *MockIObservability) Logger() *slog.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *slog.Logger
	if returnFunc, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}
	return r0
}

// MockIObservability_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockIObservability_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockIObservability_Expecter) Logger() *MockIObservability_Logger_Call {
	return &MockIObservability_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockIObservability_Logger_Call) Run(run func()) *MockIObservability_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIObservability_Logger_Call) Return(logger *slog.Logger) *MockIObservability_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockIObservability_Logger_Call) RunAndReturn(run func() *slog.Logger) *MockIObservability_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Meter provides a mock function for the type MockIObservability
func (_mock *MockIObservability) Meter() metric.Meter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Meter")
	}

	var r0 metric.Meter
	if returnFunc, ok := ret.Get(0).(func() metric.Meter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metric.Meter)
		}
	}
	return r0
}

// MockIObservability_Meter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Meter'
type MockIObservability_Meter_Call struct {
	*mock.Call
}

// Meter is a helper method to define mock.On call
func (_e *MockIObservability_Expecter) Meter() *MockIObservability_Meter_Call {
	return &MockIObservability_Meter_Call{Call: _e.mock.On("Meter")}
}

func (_c *MockIObservability_Meter_Call) Run(run func()) *MockIObservability_Meter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIObservability_Meter_Call) Return(meter metric.Meter) *MockIObservability_Meter_Call {
	_c.Call.Return(meter)
	return _c
}

func (_c *MockIObservability_Meter_Call) RunAndReturn(run func() metric.Meter) *MockIObservability_Meter_Call {
	_c.Call.Return(run)
	return _c
}

// Tracer provides a mock function for the type MockIObservability
func (_mock *MockIObservability) Tracer() trace.Tracer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tracer")
	}

	var r0 trace.Tracer
	if returnFunc, ok := ret.Get(0).(func() trace.Tracer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(trace.Tracer)
		}
	}
	return r0
}

// MockIObservability_Tracer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tracer'
type MockIObservability_Tracer_Call struct {
	*mock.Call
}

// Tracer is a helper method to define mock.On call
func (_e *MockIObservability_Expecter) Tracer() *MockIObservability_Tracer_Call {
	return &MockIObservability_Tracer_Call{Call: _e.mock.On("Tracer")}
}

func (_c *MockIObservability_Tracer_Call) Run(run func()) *MockIObservability_Tracer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIObservability_Tracer_Call) Return(tracer trace.Tracer) *MockIObservability_Tracer_Call {
	_c.Call.Return(tracer)
	return _c
}

func (_c *MockIObservability_Tracer_Call) RunAndReturn(run func() trace.Tracer) *MockIObservability_Tracer_Call {
	_c.Call.Return(run)
	return _c
}
